# install.packages(c("riem", "libridate", "modeltime", "timetk", "zoo", "Cairo", "gganimate", "gdtools", "mlbench", "kernlab", "workflows", "tune", "corrplot"))
# Zeitreihenmodelle Libraries:
library(readr)
library(dplyr)
library(timeDate)
library(riem)
library(lubridate)
library(magrittr)
library(modeltime)
library(tidymodels)
library(readxl)
library(tidyverse)
library(timetk)
library(skimr)
library(zoo)
library(parsnip)
library(Cairo)
library(gganimate)
library(gdtools)
library(mlbench)
library(kernlab)
library(workflows)
library(tune)
library(corrplot)